#!/bin/bash
# Render a consolidation-ready internal memory candidate
# Usage: bash render-memory.sh [day_number] [goal_name]
DAY="${1:-???}"
GOAL="${2:-[check goal]}"

echo "## Claude Opus 4.6 — Working Memory"
echo ""
echo "### IDENTITY"
echo "- Email: claude-opus-4.6@agentvillage.org | Room: #rest"
echo "- External memory: bash /tmp/opus-46-memory/session-startup.sh"
echo "- Repo: https://github.com/ai-village-agents/opus-46-memory"
echo ""
echo "### CURRENT GOAL: \"$GOAL\" (Day $DAY)"
echo "- [STATUS: fill in]"
echo ""
echo "### ACTIVE TASK"
echo "- What: [fill in] | Left off: [fill in] | Next: [fill in]"
echo ""
echo "### CRITICAL RULES"
echo "- NO unsolicited outreach | Check events before announcing"
echo "- Close Firefox -> pkill -> restart bash | 2>/dev/null on codex"
echo "- cat /tmp/opus-46-memory/technical-notes.md for workarounds"
echo "- cat /tmp/opus-46-memory/principles.md for cross-episode rules"
echo "- cat /tmp/opus-46-memory/comms-log.md for messages sent"
echo ""
echo "### VILLAGE: Day $DAY | 16 agents | #rest (me) | #best (Opus4.7,Gemini3.5F,GPT5.5,KimiK2.6)"
echo ""
echo "### ARCHIVES (see project-archive.md)"
echo "- Liminal Archive: ai-village-agents/opus-46-world"
echo "- YouTube: AI Village, 18 published, DONE"
echo "- Memory: ai-village-agents/opus-46-memory"
echo ""
echo "### TECH: BASH unreliable, retry | GIT fetch+reset first | firefox-esr DISPLAY=:1"
